#!/usr/bin/env bash

set -e # Exit immediately if a simple command exits with exit code >0

OLD_AWS=${AWS_CONFIG_FILE}

# Start and end time for the vms
START_TIME="9"
END_TIME="17" 

write_aws_config() {
  sed 's/"//g; s/aws_access_key = /aws_access_key_id=/g; s/aws_secret_key = /aws_secret_access_key=/g; s/aws_region = /region=/g; /aws_vpc_name/d; /aws_key_name/d;' ${PWD}/aws.tfvars > ${PWD}/aws_config 
  if [[ -z $(grep region "aws_config") ]]
  then
    echo "No region found, using us-west-2"
    echo "region=us-west-2" >> ${PWD}/aws_config
  else
    echo "Found a region in the vars."
    grep region "aws_config" 
  fi
  echo 
  if [[ -z "$(grep startup "aws_config")" ]]
  then
    echo "No 'startup' var found in config, using default '9'"
  else
    START_TIME="$(sed -n -e 's/ //g; s/startup=//p' aws_config)"
    echo "Found startup time ${START_TIME}"
  fi
  
  if [[ -z "$(grep shutdown "aws_config")" ]]
  then
    echo "No 'shutdown' var found in config, using default '17'"
  else
    END_TIME="$(sed -n -e 's/ //g; s/shutdown=//p' aws_config)"
    echo "Found shutdown time ${END_TIME}"
  fi
  echo
  echo '[default]' | cat - ${PWD}/aws_config > temp && mv temp ${PWD}/aws_config
  export AWS_CONFIG_FILE=${PWD}/aws_config
  echo "Setting AWS Config to '${AWS_CONFIG_FILE}'"
}

show_instances() {
  echo "Note if this takes substantial time, then the VPC or instances could not be found."
  vpcname=$(sed -n -e 's/"//g; s/ //g; s/=//g; s/aws_vpc_name//p' ${PWD}/aws.tfvars)
  vpc=$(aws ec2 describe-vpcs --filters Name=tag-value,Values=${vpcname} | jq -r -c '.Vpcs[] | .VpcId ')
  echo "Pulling all instances belonging to VPC named '${vpcname}' with ID '${vpc}'" 
  echo "" 
  cat ${AWS_CONFIG_FILE}
  echo "" 
  if [[ $# -eq 0 ]]; then
    aws ec2 describe-instances --filters Name=vpc-id,Values=${vpc} | jq '.Reservations[] | .Instances[] | .InstanceId' 
  else
    aws ec2 describe-instances --filters Name=vpc-id,Values=${vpc} | jq '.Reservations[] | .Instances[] | .InstanceId' | sed 's/"//g' > ${1} 
  fi 
}

cleanup() {
  rm "${AWS_CONFIG_FILE}"
  rm instance_list
  export AWS_CONFIG_FILE=${OLD_AWS}
  echo "Reset AWS Config to '${AWS_CONFIG_FILE}'."
}

shutdown_instances() {

  show_instances instance_list
  echo "* * * * * * * * * * * * * *"
  cat instance_list
  echo "* * * * * * * * * * * * * *"
  echo "About to stop all of the instances above."
  IFS=$'\n'  # make newlines the separator
  for i in `cat ./instance_list`; do
    echo "Stopping $i"
    aws ec2 stop-instances --instance-ids $i
  done
  unset IFS

}

start_instances() {
  show_instances instance_list
  echo "* * * * * * * * * * * * * *"
  cat instance_list
  echo "* * * * * * * * * * * * * *"
  echo "About to restart all of the instances above."
  IFS=$'\n'  # make newlines the separator
  for i in `cat ./instance_list`; do
    echo "Starting $i"
    aws ec2 start-instances --instance-ids $i
  done
  unset IFS
}

main() {
    # Write the config file for the AWS based on the aws.tfvars file
    # Shut down the instances with AWS cli
    # start_instances
  while true; do
    write_aws_config
    if [ ${END_TIME} -gt "$(date +"%H")" ] && [ ${START_TIME} -lt "$(date +"%H")" ]
    then
      start_instances
    else
      shutdown_instances
    fi
    # Remove the aws_config file and reset variable to the original location
    cleanup
    sleep 30m
  done
}

main "${@-help}"

exit $?
